// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbNY_gP0H4mmRfMXcBWNgW51KBL60suYs',
    appId: '1:561669857158:web:800ea06f5e0fa7722e5607',
    messagingSenderId: '561669857158',
    projectId: 'chat-app-dfde0',
    authDomain: 'chat-app-dfde0.firebaseapp.com',
    storageBucket: 'chat-app-dfde0.appspot.com',
    measurementId: 'G-7V21L96K11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpctfj1KySKuqYJrPr0rhg_4I4mZGV3SM',
    appId: '1:561669857158:android:a513cfb9974a699e2e5607',
    messagingSenderId: '561669857158',
    projectId: 'chat-app-dfde0',
    storageBucket: 'chat-app-dfde0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkW8XM2Y1kN1DvjaL8Iiv0LTs4YAC80tI',
    appId: '1:561669857158:ios:77f8e9d52210ec6b2e5607',
    messagingSenderId: '561669857158',
    projectId: 'chat-app-dfde0',
    storageBucket: 'chat-app-dfde0.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkW8XM2Y1kN1DvjaL8Iiv0LTs4YAC80tI',
    appId: '1:561669857158:ios:69569fb0fee6df402e5607',
    messagingSenderId: '561669857158',
    projectId: 'chat-app-dfde0',
    storageBucket: 'chat-app-dfde0.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
